name: Build and Rollback

on:
  push:
    branches:
      - main  # or whichever branch you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run build
        id: build
        run: npm run build

      - name: Rollback if build fails
        if: failure()
        run: |
          echo "Build failed. Rolling back..."
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git reset --hard HEAD~1
          git push origin +HEAD
